name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: psf/black@stable
        id: action_black
        with:
          src: "."
          options: "-t py311"
      - name: Get changes
        id: uncommitted_modifications
        run: git diff -r --quiet
      - name: Commit black changes
        if: ${{ failure() && steps.uncommitted_modifications.exitcode > 0 }}
        run: |
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git commit -am "GH action: Apply black formatting"
            git push origin HEAD:${GITHUB_REF}
